### ISSUE TITLE
What does it do?

### ISSUE THREAD

**Issue by PhilAndrew** [durgaswaroop/delorean#1]
It's a what type of hammer for what nail?

**Comment by vaibhavsingh1993** [comment]
This is a Version Control system a'la Git or Mercurial.

**Comment by PhilAndrew** [comment]
Your trying to make a better git?

**Comment by PhilAndrew** [comment]
Suggest you use de rather than delorean as the command to type.

**Comment by durgaswaroop** [comment]
@PhilAndrew 
> Your trying to make a better git?
Yes, that's the idea.
> Suggest you use de rather than delorean as the command to type.
Ok. Right now I've just setup an alias on my machine which runs the jar. But Yeah, will shorten it.
